services:
  backend-prod:
    container_name: news-backend-prod
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '8080:3000'
    restart: always
    environment:
      - NODE_ENV=production
