# ---- Base Stage ---
FROM node:22-slim AS base
WORKDIR /app
RUN corepack enable pnpm

# ---- Development Stage ----
FROM base AS development
WORKDIR /app

ENV PUPPETEER_CACHE_DIR=/app/.puppeteer-cache
RUN pnpm dlx puppeteer browsers install chrome

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY backend/package.json ./backend/

RUN pnpm install --frozen-lockfile

EXPOSE 3000

CMD ["pnpm", "--filter", "backend", "run", "dev"]